import React from 'react';
import styles from '../styles/Projects.module.css';

function Projects() {
  return (
    <section id="projects" className={styles.projects}>
      <h2 className={styles.projectsHeader}>Projects</h2>
      <div className={styles.projectsContainer}>
        <div className={styles.project}>
          <h3>Tic-Tac-Toe-Tango</h3>
          <p>This project is about showcasing simple logic and front end skills with ReactJS</p>
          <a href="https://github.com/alexd63/cs349_tic-tac-toe-tango" target="_blank">View Project</a>
        </div>
        <div className={styles.project}>
          <h3>FitTRAK</h3>
          <p>FitTRAK is an iOS mobile application to track exercise and food calories based on daily nutrition </p>
          <a href="https://github.com/alexd63/FitTRAK.git" target="_blank">View Project</a>
        </div>
        <div className={styles.project}>
          <h3>Notes</h3>
          <p>Simple notes app that uses MongoDB to upload and fetch notes to a database through iOS application</p>
          <a href="https://github.com/alexd63/Notes.git" target="_blank">View Project</a>
        </div>
        <div className={styles.project}>
          <h3>TrivAI</h3>
          <p>Web browser game based on trivia questions generated by ChatGPT about movies, games, books, and shows</p>
          <a href="https://github.com/alexd63/TrivAI.git" target="_blank">View Project</a>
        </div>
      </div>
    </section>
  );
}

export default Projects;
